from __future__ import annotations
from typing import Protocol, List, Optional, Dict, Any

class Repository(Protocol):
    # Clinics
    def list_clinics(self) -> List[Dict[str, Any]]: ...
    def get_clinic(self, clinic_id: str) -> Optional[Dict[str, Any]]: ...
    def upsert_clinic(self, clinic: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete_clinic(self, clinic_id: str) -> None: ...

    # Contacts
    def list_contacts(self, clinic_id: str) -> List[Dict[str, Any]]: ...
    def upsert_contact(self, contact: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete_contact(self, contact_id: str) -> None: ...

    # Visits
    def list_visits(self) -> List[Dict[str, Any]]: ...
    def get_visit(self, visit_id: str) -> Optional[Dict[str, Any]]: ...
    def upsert_visit(self, visit: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete_visit(self, visit_id: str) -> None: ...

    # Notes
    def get_note_by_visit(self, visit_id: str) -> Optional[Dict[str, Any]]: ...
    def upsert_note(self, note: Dict[str, Any]) -> Dict[str, Any]: ...
